version: '2'

services:
    odsupercomponent:
        # IMAGE=seresearch/opendlv-on-opendlv-core-on-opendavinci-on-base-dev:latest
        image: ${IMAGE}
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    #proxy-camera
    proxy-camera:
        image: ${IMAGE}
        network_mode: host
        depends_on:
            - odsupercomponent
        group_add:
            - video
        ipc: host
        user: odv
        devices:
            - "/dev/video0:/dev/video0"
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-camera --cid=${CID}  --freq=30"
        # command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-camera --cid=${CID}  --freq=20 --realtime=20"

    #proxy-ellipse2n
    #image need to be built locally
    # proxy-ellipse2n:
    #     image: "ellipseproxy:ellipsev0.0.2"
    #     network_mode: "host"
    #     devices:
    #         - "/dev/ttyUSB0:/dev/ttyUSB0"
    #     # volumes:
    #     #     - /etc/passwd:/etc/passwd
    #     #     - /etc/groups:/etc/groups
    #     command: "opendlv-proxy-ellipse2n --cid=${CID} --id=112"


    #recorder
    # odrecorderh264:
    #     image: ${IMAGE}
    #     depends_on:
    #         - odsupercomponent
    #         - proxy-camera
    #         # - proxy-velodyne16
    #         # - proxy-ellipse2n
    #     volumes:
    #         - ~/recordings:/opt/recordings
    #     user: odv
    #     network_mode: host
    #     ipc: host
    #     working_dir: "/opt/recordings"
    #     command: "/opt/od4/bin/odrecorderh264 --cid=${CID}"


    #signal-viewer
    # signal-viewer:
    #     image: chalmersrevere/opendlv-signal-viewer-multi:v0.0.4
    #     network_mode: "host"
    #     ports:
    #         - "8080:8080" 
    #     command: "--cid=${CID}"

    # #vehicle-viewer
    # vehicle-viewer:
    #     image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.8
    #     network_mode: "host"
    #     ports:
    #         - "8081:8081" 
    #     command: "--cid=${CID}"

    # odcockpit:
    #    image: ${IMAGE}
    #    network_mode: host
    #    environment:
    #    - DISPLAY=$DISPLAY
    #    volumes:
    #    - /tmp/.X11-unix:/tmp/.X11-unix
    #    #- .:/opt/opendlv.data
    #    - ~/opendlv/opendlv.cfsd18/code/logic-cfsd18/perception/detectconelane/src:/opt/testdata
    #    - ~/recordings:/opt/Recordings
    #    ipc: host
    #    user: odv
    #    depends_on:
    #        - odsupercomponent
    #    command: "/opt/od4/bin/odcockpit --cid=${CID}" 

