version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    #proxy-camera
    proxy-camera:
        image: ${IMAGE}
        network_mode: host
        privileged: true
        cap_add:
            - SYS_NICE
        depends_on:
            - odsupercomponent
        group_add:
            - video
        ipc: host
        user: root
        devices:
            - "/dev/video0:/dev/video0"
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        #command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-camera --cid=${CID}  --id=0 --freq=20"
        command: "nice -n -10 /opt/opendlv.core/bin/opendlv-core-system-proxy-camera --cid=${CID}  --freq=20"


    #recorder
    odrecorderh264:
        image: ${IMAGE}
        depends_on:
            - odsupercomponent
            - proxy-camera
        volumes:
            - ~/recordings:/opt/recordings
        user: root
        network_mode: host
        ipc: host
        working_dir: "/opt/recordings"
        command: "/opt/od4/bin/odrecorderh264 --cid=${CID}"


